[api_secrets]
#API_SECRET_KEY = "sk-zk2f30ece943512968c3d34f2763362739a65e4342e22d91"
#BASE_URL = "https://flag.smarttrot.com/v1/"
API_SECRET_KEY = "sk-9gzpobwFdEiq0uyX48655dB16eDa4dA39fCd5147D666F8C0"
##BASE_URL = "https://api.wlai.vip/v1"
BASE_URL = "https://yunwu.zeabur.app/v1"